package: v20240312
generate:
  client: true
  models: true
output-options:
  skip-prune: true
import-mapping:
  ./common/common.yaml: github.com/snyk/code-client-go/internal/workspace/2024-03-12/common
  ./links/links.yaml: github.com/snyk/code-client-go/internal/workspace/2024-03-12/links
  ./workspaces/workspaces.yaml: github.com/snyk/code-client-go/internal/workspace/2024-03-12/workspaces
  ./parameters/orgs.yaml: github.com/snyk/code-client-go/internal/workspace/2024-03-12/parameters
  ./parameters/request-id.yaml: github.com/snyk/code-client-go/internal/workspace/2024-03-12/parameters
  ./parameters/user-agent.yaml: github.com/snyk/code-client-go/internal/workspace/2024-03-12/parameters
output: client.go